name: Check Diff

on:
  push:
    branches:
      - main
      - feature/**
      - renovate/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  current-branch-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Yarn
        uses: ./.github/actions/prepare

      - name: Run Build
        run: yarn build

      - name: Upload Output Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-current
          path: out

  main-branch-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Yarn
        uses: ./.github/actions/prepare

      - name: Run Build
        run: yarn build

      - name: Upload Output Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-main
          path: out

  diff-builds:
    runs-on: ubuntu-latest

    needs:
      - current-branch-build
      - main-branch-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Output Files On Current Branch
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-current
          path: out-current

      - name: Download Output Files On Main Branch
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-main
          path: out-main

      - name: Compare Build Files
        run: diff out-current out-main
